# Generated by Django 4.0.2 on 2022-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=12)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('region', models.CharField(max_length=20)),
                ('availableResources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=12)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('region', models.CharField(max_length=20)),
                ('availableResources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=12)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('region', models.CharField(max_length=20)),
                ('availableResources', models.TextField()),
            ],
        ),
    ]
